# Generated by Django 3.2 on 2021-04-11 14:33

from django.db import migrations, models
import django.utils.timezone
import files_manager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('file_hash', models.CharField(default='', max_length=64, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=255, null=True, upload_to=files_manager.models.submit_file_path)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Files',
                'ordering': ('-date_created',),
            },
        ),
    ]
